export const states = [
  "São Paulo",
  "Rio de Janeiro",
  "Minas Gerais",
  "Espírito Santo",
  "Bahia",
  "Acre",
  "Alagoas",
  "Amazonas",
  "Amapá",
  "Ceará",
  "Distrito Federal",
  "Goiás",
  "Maranhão",
  "Mato Grosso do Sul",
  "Mato Grosso",
  "Pará",
  "Paraíba",
  "Pernambuco",
  "Piauí",
  "Paraná",
  "Rio Grande do Norte",
  "Rondônia",
  "Roraima",
  "Rio Grande do Sul",
  "Santa Catarina",
  "Sergipe",
  "Tocantins",
];
